server/app/modules/hunts/router.py, server/app/modules/hunts/service.py
Join a hunt screen backend without the location parameter.
=> Load list of hunts

server/Dockerfile, server/app/exceptions.py, server/app/main.py, server/app/modules/users/auth/models.py, server/app/modules/users/auth/router.py, server/app/modules/users/auth/service.py, server/app/modules/users/auth/util.py, server/app/modules/users/models.py, server/app/modules/users/repository.py, server/app/modules/users/router.py, server/app/modules/users/service.py, server/requirements.txt
- Added global exception handler to server
- Updated dockerfile and requirements.txt for crytographic python packages
- Implemented basic login/signup backend (subject to change)
=> Basic Login / Signup Backend (Subject To Change)

server/README.md
Added README for backend setup
=> Backend Setup README

.gitignore, server/README.md, server/app/modules/users/auth/router.py, server/docker-compose.yml, server/test.Dockerfile, server/test/client.py, server/test/run_tests.py, server/test/users/auth/test_auth.py, server/test/users/test_users.py
- Modified login / signup error codes to match monday.com assignment
- Added very basic integration testing starter code (not final, not really an expert on this so please help)
- Added testing commands to README
=> Backend Testing Startercode

server/README.md, server/app/modules/hunts/repository.py, server/app/modules/users/auth/router.py, server/app/modules/users/auth/router_models.py, server/app/modules/users/auth/service.py, server/app/modules/users/auth/util.py, server/app/modules/users/repository.py, server/app/modules/users/router.py, server/app/modules/users/router_models.py, server/app/modules/users/service.py, server/requirements.txt
- Changed from email + password authentication to username + password authentication (OAuth requires this)
- Added token authentication to all relevant user endpoints
- Other small changes
=> Protecting User Endpoints With Token Authentication

client/lib/views/instructions.dart, client/lib/views/join_hunt_view.dart
added instructions page
added linking from join_hunt
=> added instructions page

client/lib/views/bottom_nav_bar.dart, client/lib/views/hunt_history_view.dart
Hunt History rendering with mock API data (frontend-only)
=> Hunt history

client/lib/app_utils/hunt_tile.dart, client/lib/views/hunt_history_view.dart, client/lib/views/join_hunt_view.dart
Fixed history having false popup dialogs
=> Fixed history having false popup dialogs

client/lib/app_utils/hunt_tile.dart, client/lib/views/hunt_history_view.dart
Added past hunt history placements in user hunt history
=> Hunt history Placements

client/lib/app_utils/profile_avatar.dart, client/lib/app_utils/profile_text_field.dart, client/lib/views/bottom_nav_bar.dart, client/lib/views/profile_view.dart
=> Profile view (frontend-only)

client/ios/Flutter/AppFrameworkInfo.plist, client/ios/Podfile.lock, client/ios/Runner.xcodeproj/project.pbxproj, client/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, client/ios/Runner.xcworkspace/contents.xcworkspacedata, client/lib/apis/api_client.dart, client/lib/apis/auth_api.dart, client/lib/errors/flash_error.dart, client/lib/storage/secure_storage.dart, client/lib/views/create_account_view.dart, client/lib/views/sign_in_view.dart, client/pubspec.lock, client/pubspec.yaml, client/windows/flutter/generated_plugin_registrant.cc, client/windows/flutter/generated_plugins.cmake
- Created api layer
- Added flash errors
- Added secure storage
- E2E login & signup
=> E2E - Login & Signup

client/lib/app_utils/profile_text_field.dart, client/lib/views/profile_view.dart
- Refactored profile view code
- Added regex field validation
- Added confirm changes button
=> Refactored Profile View frontend

server/app/main.py, server/app/modules/teams/repository.py, server/app/modules/teams/router.py, server/app/modules/teams/router_models.py, server/app/modules/teams/service.py, server/app/modules/teams/team_models.py
1) Set-up teams folder
2) Added API endpoint to create a new team
=> Teams update

client/lib/apis/api_utils/token.dart, client/lib/apis/profile_api.dart, client/lib/app_utils/profile_text_field.dart, client/lib/views/profile_view.dart, client/pubspec.lock, client/pubspec.yaml
- Created profile api service
- E2E Profile Page 
- Extracted get authorization token into util file
- Added flutter toast error pop-ups
=> E2E - Profile Page

client/lib/entities/team.dart, client/lib/entities/upcoming_hunt.dart, client/lib/service/teams_service.dart, client/lib/service/upcoming_hunts_service.dart, client/lib/views/join_hunt_view.dart, client/lib/views/join_team_view.dart, client/lib/views/profile_view.dart, client/lib/views/sign_in_view.dart, client/pubspec.lock, client/pubspec.yaml, server/app/main.py, server/app/modules/hunts/router.py, server/app/modules/hunts/service.py, server/app/modules/hunts/teams/repository.py, server/app/modules/hunts/teams/router.py, server/app/modules/hunts/teams/router_models.py
Hunts and teams - what's been done so far
=> Show available hunts

client/lib/views/hunt_history_view.dart, client/lib/views/profile_view.dart
Completed fix of back arrow bug
=> Finished removing of back arrows

server/app/modules/teams/repository.py, server/app/modules/teams/router.py, server/app/modules/teams/router_models.py, server/app/modules/teams/service.py, server/app/modules/teams/team_models.py, server/scripts/add_teams.py
=> Teams branch

server/app/modules/teams/router_models.py, server/scripts/add_hunts.py, server/scripts/add_teams.py, server/scripts/main_script.py, server/scripts/py_add_users.py
1) Modified main_script to remove exec
2) Hunt_id now works
=> Main script scripted

client/lib/apis/auth_api.dart, client/lib/views/profile_view.dart
=> Implemented logout functionality

server/app/modules/teams/repository.py
This change fixes the error when the gameState for a hunt is None.
=> Fix gameState error

server/scripts/add_teams.py, server/scripts/py_add_users.py
1) Removed unnecessary code that was accessing the database
=> Removed database code

client/lib/app_utils/leaderboard_tile.dart, client/lib/views/leaderboard_view.dart
implements the leaderboard view
=> Leaderboard view

server/scripts/add_hunts.py
Added 3 new sample hunt scripts
=> Hunt Scripts

server/app/modules/teams/router.py
Updates the join team and get teams endpoints.
=> Update Teams Router

client/lib/apis/auth_api.dart, client/lib/views/authentication/create_account_view.dart, client/lib/views/authentication/sign_in_view.dart, client/lib/views/splash.dart, server/app/modules/users/auth/router.py, server/app/modules/users/auth/router_models.py, server/app/modules/users/auth/util.py
- Added exp value to login/signup endpoint responses
- Used exp value to determine whether to go to login screen or home screen on app startup
=> Smart Startup

client/lib/app_utils/team_options.dart, client/lib/reusables/hunt_structure.dart, client/lib/views/dashboard/join_hunt_options/join_team_view.dart, client/lib/views/dashboard/join_hunt_view.dart, server/app/modules/hunts/router.py, server/app/modules/hunts/router_models.py, server/scripts/add_teams.py
Hunts now have their teams populated from the database. Not entirely complete (still need to implement capacity constraints), but now matches much better with the design
=> Teams now populated from Mongo

client/lib/reusables/hunt_structure.dart, client/lib/views/dashboard/join_hunt_options/join_team_view.dart, server/app/modules/teams/router_models.py, server/scripts/add_teams.py
Implemented capacity contraints and locking for teams
=> Capacity and locking features for teams

client/lib/app_utils/hunt_tile.dart
Bug fix to get Flutter to launch
=> Updated HuntTile()

client/lib/views/dashboard/join_hunt_options/join_team_view.dart, client/lib/views/dashboard/join_hunt_view.dart
- Display a message when there are no hunts
- Display a message when there are no teams
=> Displays messages when no hunts or teams

client/lib/apis/teams_api.dart, server/app/modules/hunts/hunt_models.py
- Fixed create-teams endless loading
=> Resolved create-team bug

client/lib/views/dashboard/join_hunt_view.dart, client/lib/views/hunt/get_ready_hunt.dart, client/lib/views/hunt/mock_question.dart, client/lib/views/team/edit_team_view.dart
- Linked hunt-challenges page to my-team page
=> Linked up hunt-challenge screen

client/lib/apis/auth_api.dart, client/lib/apis/profile_api.dart, client/lib/app_utils/basic_text_field.dart, client/lib/views/authentication/sign_in_view.dart
- Minor edits to user side credential checking for login/signup
- Added error logging for login/signup and profile updates (status codes and corresponding error messages visible on the frontend)
=> Error logging - Login/Signup

client/lib/apis/api_utils/stream_request.dart, client/lib/views/dashboard/join_hunt_view.dart, client/lib/views/profile_view.dart, server/app/modules/game/teams/router.py, server/app/modules/game/teams/service.py, server/app/modules/users/auth/router.py
- Fixed Signup/login error where creating an account would throw an error
- Various bug fixes including changing the color of the text on the profile screen to be white instead of dark blue, removing the back button on the Join Hunt screen
- Removed some commented-out code and print statements intended for debugging
=> Fixed signup/login issue, plus other small bug fixes

client/lib/apis/teams_api.g.dart, client/lib/reusables/hunt_structure.dart, client/lib/reusables/hunt_structure.g.dart, client/lib/views/dashboard/join_hunt_view.dart, server/scripts/add_hunts.py
- Fixed the issue, which has to do with the implementation of number and date ranges as answers to questions
- Currently the schema does not work if the list of possible answers is not explicitly given, as opposed to providing a minAnswer and maxAnswer as a range
=> Fixed issue of hunts not loading
